### PR TITLE
Fixes based on reviews for PR #12.

### LINKED ISSUE #16: Fixes based on reviews.

### PR DESCRIPTION
**Pull request by eshaanks**
Fixes #16 
Removed "RowAction.jsx" in Contacts/Table to avoid prop drillings while defining the Table Column.

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 1]
```diff
@@ -1,11 +1,28 @@
...
+    value: "uxDesigner",
+  },
+  {
+    label: "Tester",
+    value: "tester",
+  },
+  {
+    label: "Analyst",
+    value: "analyst",
+  },
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js:25]: Create a `buildSelectOption` global(should be kept at `src/utils/index.js`) utility function that can provide `label` and camelCased `value`.
```suggestion
export const ROLES = [
  "UX designer",
  "Tester",
  "Analyst",
  "Back-end developer",
  "Front-end developer",
].map(buildSelectOption);
```

File: app/javascript/src/components/Dashboard/Contacts/utils.jsx [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import dayjs from "dayjs";
+import { MenuHorizontal } from "neetoicons";
+import { Dropdown } from "neetoui";
+
+import Avatar from "./Table/Avatar";
+
+export const convertDateToStdFormat = date =>
+  dayjs(date).format("MMM, d, YYYY");
+
+export const getColumnDefintion = setShowDeleteAlert => [
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/utils.jsx:12]:
```suggestion
export const getColumnDefintions = setShowDeleteAlert => [
```

**Review by yedhink — CHANGES_REQUESTED** [review]
@eshaanks The PR title doesn't follow the guidelines mentioned at https://handbook.neetokb.com/articles/git-and-github-essentials. Please fix it along with the following review comments.

File: app/javascript/src/components/Dashboard/Contacts/constants.js (hunk 1 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:25]: I have few doubts regarding this , what exactly does the buildSelectOption function do? Does it just convert label to camel case and return an Object like this for value in array :-  { 
                                                                                label : "String Normal",
                                                                                value: "stringNormal",
                                                                           }

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:25]: @eshaanks Yes. Exactly.

You can even go one step ahead and do it like this:

```js
const ROLES = buildSelectOptions(["Tester", "UX Designer"]); // this is better actually
```

Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:25]: I have already built the former functionality , so can I stick to it?

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:25]: @eshaanks You can actually change the logic to https://github.com/eshaanks/neeto-ui-challenge/pull/19#discussion_r973035094 since that is a better implementation.

Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:25]: I have made changes , will be reflected in the next PR.
