### PR TITLE
Fix enforcing react conventions and removing inconsistencies.

### LINKED ISSUE #11: Fix to enforce React Best Practices.

### PR DESCRIPTION
**Pull request by eshaanks**
Replaced all functions with arrow functions.
Fixed erroneous setState hooks.
removed unnecessary comments.
Made import statements consistent and stable.
Fixed disparity in form initial values and actual form data types.
Fixed yup validations for both contact and note forms.
Fixed cancel button so as to follow react best practices.

Fixes #11

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
+import React from "react";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx:1]: This is not a file that exports any React components and thus it doesn't make sense to name this file in PascalCase.

Except the `COLUMN_DATA` all other things ought to be moved to `constants.js`.

Refer: https://github.com/eshaanks/neeto-ui-challenge/pull/8#discussion_r971923751

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 2]
```diff
@@ -22,55 +22,12 @@ export const CONTACT_FORM_VALIDATION_SCHEMA = yup.object().shape({
     .string()
     .email("Invalid email format")
     .required("Email is required"),
-  role: yup.object().required("Role is required").nullable(),
+  role: yup
+    .object()
+    .nullable()
+    .shape({
+      label: yup.string().oneOf(ROLES),
+      value: yup.string().oneOf(ROLES),
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js:30]: The value should be the sluggified version of the label. Because we will have use cases with the value like say string comparison. So it's preferred to keep the value as a slug. Label can be kept as it's.

File: app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx [hunk 3]
```diff
@@ -7,14 +7,26 @@ import Form from "./Form";
 const EditNotePane = ({ fetchNotes, showPane, setShowPane, note }) => {
   const onClose = () => setShowPane(false);
 
+  const convertNoteToFormFormat = note => ({
+    title: note.title,
+    description: note.description,
+    contact: null,
+    tags: [],
+  });
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx:15]: Move this to an utils.js within the closest scope. We should try our level best to keep the presentation logic as clean as possible.

File: app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx [hunk 4]
```diff
@@ -16,9 +14,10 @@ import {
 
 const NoteForm = ({ onClose, refetch, note, isEdit }) => {
   const [submitted, setSubmitted] = useState(false);
-
   const handleSubmit = async values => {
     try {
+      // eslint-disable-next-line no-console
+      console.log(values);
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx:20]: This just wrong. You should not commit any file that has `console.log` statements. That's why we have added the eslint rules. If you are disabling those rules, then it defeats the whole purpose of those rules.

File: app/javascript/src/components/Dashboard/Notes/Utils.js [hunk 5]
```diff
@@ -0,0 +1,6 @@
+import dayjs from "dayjs";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Utils.js:1]: Wrong naming followed for the file. It's a lack of self-review that is evident. Otherwise this would've been caught. Thus attaching the self-review document once again and watch the video once again if need be:
- https://handbook.neetokb.com/articles/git-and-github-essentials#self-review-process

Note: This is a warning from my end. Further lack of self-review will have consequences.

Also read: https://academy.bigbinary.com/learn-react/pages/naming-conventions-in-react

**Review by yedhink — COMMENTED** [review]
@eshaanks

File: app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx (hunk 4 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx:20]: I think i have rectified these statements in later PR.

File: app/javascript/src/components/Dashboard/Notes/Utils.js (hunk 5 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: Sorry for the mistake, I did check these statements for quite some time. I shall find out what is wrong fix it ASAP.

File: app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx (hunk 3 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx:15]: Will fix it ASAP.

File: app/javascript/src/components/Dashboard/Notes/Utils.js (hunk 5 above)
Comment (yedhink) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: @eshaanks The filename is what is wrong. You have named this file as if it's a React component, whereas it's not.

File: app/javascript/src/components/Dashboard/Contacts/constants.js (hunk 2 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:30]: So i should convert label:"UX Designer" to value:"ux_designer" ?

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:30]: Slugs are always hyphenated(`-`). On second thoughts, rather than using a slug, it's better to use a camelCase version for the `value`. This way we can utilise the value as a JavaScript variable if need be.

```js
{
 label: "Email Field",
 value: "emailField"
}
```

File: app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx (hunk 1 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx:1]: After shifting all except COLUMN_DATA how should we name the file?

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx:1]: @eshaanks After doing that this file only contains two literal constants. Thus this file should be named `constants.js`.

File: app/javascript/src/components/Dashboard/Notes/Utils.js (hunk 5 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: Will rectify this.

File: app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx (hunk 1 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx:1]: Yedhin , I might be misunderstanding  this. Since the reason why I shifted the code from constants.js file in the first place to avoid having 'jsx' code in a 'js' file. So after moving the literal constants to constants.js (the ROW_DATA and DUMMY_CONTACT_DATA) we are left with COLUMN_DATA but it has 'jsx'. So should I name it constants.jsx or something else. 
PS: I have changed the column definitions to show delete alerts on delete click, hence now it is a function. Therefore i have named it ColumnDefinition as we would name a react component file. Is this alright?

File: app/javascript/src/components/Dashboard/Contacts/constants.js (hunk 2 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:30]: I have made necessary changes and the changes will be reflected in next PR.

File: app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx (hunk 3 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx:15]: Fixed it.

File: app/javascript/src/components/Dashboard/Notes/Utils.js (hunk 5 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: I am encountering some sort of bug where I have the file name in lower case (utils.js) in my local file directory but when I am pushing it still is showing the file name as 'Utils.js' . What may be the cause for this?

Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: It was fixed by changing my git config via this command `git config core.ignorecase false`. It seems the changes in file name are reflected properly.

Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: It seems that I needed to add some new lines to my git config so file name changes like changing the case will be caught.`git config core.ignorecase false`, is this okay?

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: @eshaanks That settings seems unnecessary. You should be moving the file using `git mv`. Refer: https://stackoverflow.com/a/20907647

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: Make sure to revert the git config change that you have made:
image

File: app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx (hunk 1 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/Table/ColumnRowDefinitions.jsx:1]: Moved ROW_DATA and DUMMY_CONTACT_DATA constants to constants.js, Moved the getColumnDefinition function to utils.jsx (renamed utils.js to utils.jsx) and rectified all pertinent imports.

File: app/javascript/src/components/Dashboard/Contacts/constants.js (hunk 2 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Contacts/constants.js:30]: Converted all occurences of such values to their respective label converted to camel case. The changes are reflected in constants.js file in both Contacts folder and Notes folder .

File: app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx (hunk 3 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Pane/Edit.jsx:15]: Moved convertNoteToFormFormat to utils.jsx in Contacts folder and changed all pertinent imports.

File: app/javascript/src/components/Dashboard/Notes/Utils.js (hunk 5 above)
Comment (eshaanks) [reply app/javascript/src/components/Dashboard/Notes/Utils.js:1]: I have removed the faulty settings that caused a duplicate Utils.jsx to be spawned within the repo. I have deleted the duplicate and renamed the original to 'utils.jsx' .
